/**
 * GOOGLE DEVICES - Database dispositivi Google Pixel
 * Pixel series completa con foldables
 */

import { DeviceSpecs, calculateMillimetricFontSize } from './types';

// 📱 GOOGLE PIXEL DEVICES
export const GoogleDevices: DeviceSpecs[] = [
  // Pixel 9 Series (2024)
  {
    brand: 'Google',
    model: 'Pixel 9a',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2024,
    marketShare: 1.8,
  },
  {
    brand: 'Google',
    model: 'Pixel 9 Pro XL',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2024,
    marketShare: 1.2,
  },
  {
    brand: 'Google',
    model: 'Pixel 9 Pro Fold',
    width: 673,
    height: 841,
    scaleFactor: 673 / 393,
    calculatedFontSize: calculateMillimetricFontSize(673),
    year: 2024,
    marketShare: 0.9,
  },
  {
    brand: 'Google',
    model: 'Pixel 9 Pro',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2024,
    marketShare: 1.5,
  },
  {
    brand: 'Google',
    model: 'Pixel 9',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2024,
    marketShare: 2.1,
  },
  // Pixel 8 Series (2023)
  {
    brand: 'Google',
    model: 'Pixel 8a',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2023,
    marketShare: 1.6,
  },
  {
    brand: 'Google',
    model: 'Pixel 8 Pro',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2023,
    marketShare: 1.4,
  },
  {
    brand: 'Google',
    model: 'Pixel 8',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2023,
    marketShare: 1.8,
  },
  // Pixel Fold
  {
    brand: 'Google',
    model: 'Pixel Fold',
    width: 673,
    height: 841,
    scaleFactor: 673 / 393,
    calculatedFontSize: calculateMillimetricFontSize(673),
    year: 2023,
    marketShare: 0.6,
  },
  // Pixel 7 Series (2022)
  {
    brand: 'Google',
    model: 'Pixel 7a',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2022,
    marketShare: 1.3,
  },
  {
    brand: 'Google',
    model: 'Pixel 7 Pro',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2022,
    marketShare: 1.1,
  },
  {
    brand: 'Google',
    model: 'Pixel 7',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2022,
    marketShare: 1.5,
  },
  // Pixel 6 Series (2021)
  {
    brand: 'Google',
    model: 'Pixel 6a',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2021,
    marketShare: 1.0,
  },
  {
    brand: 'Google',
    model: 'Pixel 6 Pro',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2021,
    marketShare: 0.8,
  },
  {
    brand: 'Google',
    model: 'Pixel 6',
    width: 412,
    height: 915,
    scaleFactor: 412 / 393,
    calculatedFontSize: calculateMillimetricFontSize(412),
    year: 2021,
    marketShare: 1.2,
  },
];
